# Comment to be posted on PRs from first-time contributors in Novu repository
newPRWelcomeComment: |
  Thank you for opening this pull request and contributing to Novu! :tada:
  Your PR will be reviewed by a Novu team member as soon as possible. :rocket:

# Comment to be posted on first-time issues
newIssueWelcomeComment: >
  Thank you for opening your first issue here! 🛠
