# Comment to be posted on PRs from first-time contributors in Novu repository
newPRWelcomeComment: |
  Thank you for opening your first pull request and contributing to Novu! :tada:
  Your PR will be reviewed by a Novu team member as soon as possible. In the meanwhile, please check that you have followed the PR template and provided as much information regarding your contribution. :rocket:
  You can also join our [Discord](https://discord.novu.co/) channel for support and discussing new ideas.
